import type {Config} from 'eslint/config';

export const eslintRules: NonNullable<Config['rules']> = {
  'arrow-body-style': ['error', 'as-needed'],
  'default-case-last': 'error',
  'default-case': 'error',
  'dot-notation': 'error',
  'func-names': 'error',
  'grouped-accessor-pairs': ['error', 'getBeforeSet'],
  'new-cap': 'error',
  'no-alert': 'error',
  'no-await-in-loop': 'error',
  'no-bitwise': 'error',
  'no-caller': 'error',
  'no-continue': 'error',
  'no-div-regex': 'error',
  'no-duplicate-imports': 'error',
  'no-else-return': 'error',
  'no-eval': 'error',
  'no-extend-native': 'error',
  'no-extra-bind': 'error',
  'no-extra-label': 'error',
  'no-implicit-coercion': ['error', {allow: ['!!']}],
  'no-implicit-globals': 'error',
  'no-implied-eval': 'error',
  'no-inner-declarations': [
    'error',
    'both',
    {blockScopedFunctions: 'disallow'},
  ],
  'no-iterator': 'error',
  'no-label-var': 'error',
  'no-labels': 'error',
  'no-lone-blocks': 'error',
  'no-lonely-if': 'error',
  'no-multi-assign': 'error',
  'no-multi-str': 'error',
  'no-negated-condition': 'error',
  'no-nested-ternary': 'error',
  'no-new-func': 'error',
  'no-new-wrappers': 'error',
  'no-new': 'error',
  'no-object-constructor': 'error',
  'no-octal-escape': 'error',
  'no-param-reassign': 'error',
  'no-plusplus': 'error',
  'no-promise-executor-return': 'error',
  'no-proto': 'error',
  'no-return-assign': 'error',
  'no-script-url': 'error',
  'no-sequences': 'error',
  'no-throw-literal': 'error',
  'no-undef-init': 'error',
  'no-unmodified-loop-condition': 'error',
  'no-unneeded-ternary': ['error', {defaultAssignment: false}],
  'no-unreachable-loop': 'error',
  'no-useless-call': 'error',
  'no-useless-computed-key': 'error',
  'no-useless-concat': 'error',
  'no-useless-constructor': 'error',
  'no-useless-rename': 'error',
  'no-useless-return': 'error',
  'no-var': 'error',
  'no-void': ['error', {allowAsStatement: false}],
  'no-warning-comments': 'error',
  'object-shorthand': 'error',
  'prefer-arrow-callback': 'error',
  'prefer-const': ['error', {destructuring: 'all'}],
  'prefer-exponentiation-operator': 'error',
  'prefer-named-capture-group': 'error',
  'prefer-numeric-literals': 'error',
  'prefer-object-has-own': 'error',
  'prefer-object-spread': 'error',
  'prefer-promise-reject-errors': 'error',
  'prefer-regex-literals': ['error', {disallowRedundantWrapping: true}],
  'prefer-rest-params': 'error',
  'prefer-spread': 'error',
  'prefer-template': 'error',
  'preserve-caught-error': ['error', {requireCatchParameter: true}],
  'require-unicode-regexp': 'error',
  'symbol-description': 'error',
  curly: ['error', 'multi-line', 'consistent'],
  eqeqeq: 'error',
  radix: 'error',
  strict: ['error', 'global'],
  yoda: 'error',
  'no-restricted-properties': [
    'error',
    {
      object: 'global',
      property: 'isFinite',
      message: 'Please use `Number.isFinite` instead.',
    },
    {
      object: 'self',
      property: 'isFinite',
      message: 'Please use `Number.isFinite` instead.',
    },
    {
      object: 'window',
      property: 'isFinite',
      message: 'Please use `Number.isFinite` instead.',
    },
    {
      object: 'global',
      property: 'isNaN',
      message: 'Please use `Number.isNaN` instead.',
    },
    {
      object: 'self',
      property: 'isNaN',
      message: 'Please use `Number.isNaN` instead.',
    },
    {
      object: 'window',
      property: 'isNaN',
      message: 'Please use `Number.isNaN` instead.',
    },
  ],
  'no-restricted-syntax': [
    'error',
    {
      selector: 'ForInStatement',
      message:
        'for..in loops iterate over the entire prototype chain, which is most likely an error. Use `for..of` or `Object.values` instead.',
    },
    {
      selector: 'MemberExpression[object.name="JSON"][property.name="parse"]',
      message:
        '`JSON.parse` returns `any` type. Use `jsonParse` from `@monholm/util` instead',
    },
    {
      selector:
        'MemberExpression[object.name="Array"][property.name="isArray"]',
      message:
        '`Array.isArray` returns `any[]` type. Use `isArray` from `@monholm/util` instead',
    },
    {
      selector: 'Identifier[name="Omit"]',
      message:
        '`Omit` is not type safe (does not show any error if omitting a key that does not exist). Use `Except` from `type-fest` instead',
    },
  ],
  'no-restricted-globals': [
    'error',
    {name: 'isFinite', message: 'Use `Number.isFinite` instead.'},
    {name: 'isNaN', message: 'Use `Number.isNaN` instead.'},
  ],
};
