import type {Config} from 'eslint/config';

export const reactRules: NonNullable<Config['rules']> = {
  'react/button-has-type': 'error',
  'react/checked-requires-onchange-or-readonly': 'error',
  'react/default-props-match-prop-types': 'error',
  'react/display-name': 'error',
  'react/forward-ref-uses-ref': 'error',
  'react/hook-use-state': 'error',
  'react/iframe-missing-sandbox': 'error',
  'react/jsx-boolean-value': 'error',
  'react/jsx-child-element-spacing': 'error',
  'react/jsx-closing-tag-location': 'error',
  'react/jsx-curly-brace-presence': [
    'error',
    {props: 'never', children: 'never', propElementValues: 'always'},
  ],
  'react/jsx-equals-spacing': 'error',
  'react/jsx-filename-extension': [
    'error',
    {
      allow: 'as-needed',
      extensions: ['.jsx', '.tsx'],
      ignoreFilesWithoutCode: true,
    },
  ],
  'react/jsx-fragments': 'error',
  'react/jsx-key': [
    'error',
    {
      checkFragmentShorthand: true,
      checkKeyMustBeforeSpread: true,
      warnOnDuplicates: true,
    },
  ],
  'react/jsx-no-bind': [
    'error',
    {
      ignoreRefs: true,
      allowArrowFunctions: true,
      allowFunctions: false,
      allowBind: false,
      ignoreDOMComponents: true,
    },
  ],
  'react/jsx-no-comment-textnodes': 'error',
  'react/jsx-no-constructed-context-values': 'error',
  'react/jsx-no-duplicate-props': 'error',
  /*
   * jsx-no-leaked-render isn't type aware, meaning it report errors even on boolean expressions.
   * To use it, you have to always use `!!` or `Boolean()` to cast your expressions to booleans,
   * which in turn will cause @typescript-eslint/no-unnecessary-type-conversion to report errors.
   * So instead of using it, we stricten our use of strict-boolean-expressions to disallow anything besides booleans
   * in react projects.
   */
  'react/jsx-no-leaked-render': 'off',
  '@typescript-eslint/strict-boolean-expressions': [
    'error',
    {
      allowAny: false,
      allowNullableBoolean: false,
      allowNullableEnum: false,
      allowNullableNumber: false,
      allowNullableObject: false,
      allowNullableString: false,
      allowNumber: false,
      allowRuleToRunWithoutStrictNullChecksIKnowWhatIAmDoing: false,
      allowString: false,
    },
  ],
  'react/jsx-no-script-url': 'error',
  'react/jsx-no-target-blank': [
    'error',
    {enforceDynamicLinks: 'always', warnOnSpreadAttributes: true},
  ],
  'react/jsx-no-undef': 'error',
  'react/jsx-no-useless-fragment': 'error',
  'react/jsx-pascal-case': 'error',
  'react/jsx-props-no-multi-spaces': 'error',
  'react/jsx-props-no-spread-multi': 'error',
  'react/jsx-tag-spacing': [
    'error',
    {
      closingSlash: 'never',
      beforeSelfClosing: 'always',
      afterOpening: 'never',
      beforeClosing: 'never',
    },
  ],
  'react/jsx-uses-vars': 'error',
  'react/no-access-state-in-setstate': 'error',
  'react/no-array-index-key': 'error',
  'react/no-arrow-function-lifecycle': 'error',
  'react/no-children-prop': 'error',
  'react/no-danger': 'error',
  'react/no-danger-with-children': 'error',
  'react/no-deprecated': 'error',
  'react/no-did-mount-set-state': ['error', 'disallow-in-func'],
  'react/no-did-update-set-state': ['error', 'disallow-in-func'],
  'react/no-direct-mutation-state': 'error',
  'react/no-find-dom-node': 'error',
  'react/no-invalid-html-attribute': 'error',
  'react/no-is-mounted': 'error',
  'react/no-namespace': 'error',
  'react/no-object-type-as-default-prop': 'error',
  'react/no-redundant-should-component-update': 'error',
  'react/no-render-return-value': 'error',
  'react/no-string-refs': ['error', {noTemplateLiterals: true}],
  'react/no-this-in-sfc': 'error',
  'react/no-typos': 'error',
  'react/no-unescaped-entities': 'error',
  'react/no-unknown-property': ['error', {requireDataLowercase: true}],
  'react/no-unstable-nested-components': 'error',
  'react/no-unused-class-component-methods': 'error',
  'react/no-unused-prop-types': 'error',
  'react/no-unused-state': 'error',
  'react/no-will-update-set-state': ['error', 'disallow-in-func'],
  'react/prefer-es6-class': 'error',
  'react/prefer-exact-props': 'error',
  'react/prefer-stateless-function': 'error',
  'react/prop-types': 'error',
  'react/require-render-return': 'error',
  'react/self-closing-comp': 'error',
  'react/state-in-constructor': 'error',
  'react/void-dom-elements-no-children': 'error',
  'react/function-component-definition': [
    'error',
    {
      namedComponents: ['function-declaration', 'arrow-function'],
      unnamedComponents: 'arrow-function',
    },
  ],
};
